/** Shared labels so signal extraction and UI stay aligned. */
export const BUSAN_DISTRICT_LABELS = [
  "중구",
  "서구",
  "동구",
  "영도구",
  "부산진구",
  "동래구",
  "남구",
  "북구",
  "해운대구",
  "사하구",
  "금정구",
  "강서구",
  "연제구",
  "수영구",
  "사상구",
  "기장군",
] as const;

/** Colloquial short names → official district labels (longer aliases first in extraction). */
export const BUSAN_DISTRICT_ALIASES: Record<string, string> = {
  해운대: "해운대구",
  부산진: "부산진구",
  진구: "부산진구",
  동래: "동래구",
  영도: "영도구",
  기장: "기장군",
  금정: "금정구",
  연제: "연제구",
  수영: "수영구",
  사상: "사상구",
  사하: "사하구",
  강서: "강서구",
};

export const QUERY_SUGGESTIONS = [
  "고령 인구 대비 병원이 부족한 곳",
  "의료 취약 지역 순위",
  "사망자가 많은 동",
  "출생이 많은 지역",
  "자연감소가 큰 곳",
  "인구밀도가 높은 동",
  "총인구가 많은 지역",
  "고령화율이 높은 곳",
  "최근접 의료기관 거리가 먼 동",
  "2km 안에 병원이 적은 곳",
  "기장군과 강서구 비교",
  "해운대구 상세 지표",
  "해운대 근처 병원",
  "종합병원 위치",
  "약국만 보여줘",
  "인구가 늘어나는 지역",
  "1인가구 비중이 높은 동",
  "어디가 제일 의료 취약해",
  "수영구 인구 현황",
  "야간 진료 병원",
  "주말 여는 약국",
  "해운대 vs 수영 비교",
  "3km 반경 접근성",
  "치과 많은 곳",
] as const;
